ALTER TABLE posts ADD COLUMN slug TEXT;
ALTER TABLE posts ADD COLUMN template TEXT NOT NULL DEFAULT 'content';
ALTER TABLE posts ADD COLUMN sortOrder INTEGER NOT NULL DEFAULT 10;
ALTER TABLE posts ADD COLUMN contentEn TEXT NOT NULL DEFAULT '{}';
ALTER TABLE posts ADD COLUMN contentLv TEXT NOT NULL DEFAULT '{}';
ALTER TABLE posts ADD COLUMN settings TEXT NOT NULL DEFAULT '{}';

CREATE UNIQUE INDEX IF NOT EXISTS postsSlugIdx ON posts (slug);
CREATE INDEX IF NOT EXISTS postsTemplateOrderIdx ON posts (template, sortOrder);

CREATE TABLE IF NOT EXISTS media (
  id TEXT PRIMARY KEY NOT NULL,
  filename TEXT NOT NULL,
  mimeType TEXT NOT NULL,
  size INTEGER NOT NULL,
  altEn TEXT NOT NULL DEFAULT '',
  altLv TEXT NOT NULL DEFAULT '',
  createdAt INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS mediaCreatedAtIdx ON media (createdAt);
