/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    events: Event;
    'special-pages': SpecialPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'special-pages': SpecialPagesSelect<false> | SpecialPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'main-menu': MainMenu;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Used only in the Payload admin.
   */
  adminTitle: string;
  slug: string;
  order: number;
  en: {
    title: string;
    /**
     * A short summary used on cards and listing pages.
     */
    excerpt: string;
  };
  lv: {
    title: string;
    /**
     * A short summary used on cards and listing pages.
     */
    excerpt: string;
  };
  layout: (HeroLayoutBlock | ContentLayoutBlock | CallToActionLayoutBlock)[];
  meta?: {
    /**
     * Optional search/social title. Defaults to the English page title.
     */
    title?: string | null;
    /**
     * Optional search/social description. Defaults to the English excerpt.
     */
    description?: string | null;
    /**
     * Recommended size: 1200 × 630 pixels.
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroLayoutBlock".
 */
export interface HeroLayoutBlock {
  en: {
    eyebrow?: string | null;
    heading: string;
    text: string;
  };
  lv: {
    eyebrow?: string | null;
    heading: string;
    text: string;
  };
  image?: (number | null) | Media;
  alignment?: ('left' | 'center') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentLayoutBlock".
 */
export interface ContentLayoutBlock {
  en: {
    heading?: string | null;
    /**
     * Separate paragraphs with a blank line.
     */
    body: string;
  };
  lv: {
    heading?: string | null;
    /**
     * Separate paragraphs with a blank line.
     */
    body: string;
  };
  image?: (number | null) | Media;
  imagePosition?: ('right' | 'left' | 'none') | null;
  tone?: ('plain' | 'muted') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionLayoutBlock".
 */
export interface CallToActionLayoutBlock {
  en: {
    heading: string;
    text?: string | null;
    buttons?:
      | {
          label: string;
          link: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  lv: {
    heading: string;
    text?: string | null;
    buttons?:
      | {
          label: string;
          link: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Used only in the Payload admin.
   */
  adminTitle: string;
  slug: string;
  order: number;
  accentTone: 'emerald' | 'amber' | 'sky' | 'rose' | 'violet' | 'slate';
  /**
   * Recommended: landscape image at least 1200 × 800 pixels.
   */
  image?: (number | null) | Media;
  en: {
    title: string;
    body: string;
  };
  lv: {
    title: string;
    body: string;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-pages".
 */
export interface SpecialPage {
  id: number;
  /**
   * Used only in the Payload admin.
   */
  adminTitle: string;
  slug: string;
  en: {
    title: string;
    /**
     * Separate paragraphs with a blank line.
     */
    content: string;
  };
  lv: {
    title: string;
    /**
     * Separate paragraphs with a blank line.
     */
    content: string;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'special-pages';
        value: number | SpecialPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  adminTitle?: T;
  slug?: T;
  order?: T;
  en?:
    | T
    | {
        title?: T;
        excerpt?: T;
      };
  lv?:
    | T
    | {
        title?: T;
        excerpt?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroLayoutBlockSelect<T>;
        content?: T | ContentLayoutBlockSelect<T>;
        cta?: T | CallToActionLayoutBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroLayoutBlock_select".
 */
export interface HeroLayoutBlockSelect<T extends boolean = true> {
  en?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  lv?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  image?: T;
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentLayoutBlock_select".
 */
export interface ContentLayoutBlockSelect<T extends boolean = true> {
  en?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  lv?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  image?: T;
  imagePosition?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionLayoutBlock_select".
 */
export interface CallToActionLayoutBlockSelect<T extends boolean = true> {
  en?:
    | T
    | {
        heading?: T;
        text?: T;
        buttons?:
          | T
          | {
              label?: T;
              link?: T;
              variant?: T;
              id?: T;
            };
      };
  lv?:
    | T
    | {
        heading?: T;
        text?: T;
        buttons?:
          | T
          | {
              label?: T;
              link?: T;
              variant?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  adminTitle?: T;
  slug?: T;
  order?: T;
  accentTone?: T;
  image?: T;
  en?:
    | T
    | {
        title?: T;
        body?: T;
      };
  lv?:
    | T
    | {
        title?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-pages_select".
 */
export interface SpecialPagesSelect<T extends boolean = true> {
  adminTitle?: T;
  slug?: T;
  en?:
    | T
    | {
        title?: T;
        content?: T;
      };
  lv?:
    | T
    | {
        title?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  en: {
    heroEyebrow: string;
    heroTitle: string;
    heroSubtitle: string;
    heroPrimaryLabel: string;
    heroSecondaryLabel: string;
    eventsTitle: string;
    eventsIntro: string;
    exploreEyebrow: string;
    exploreTitle: string;
    exploreIntro: string;
  };
  lv: {
    heroEyebrow: string;
    heroTitle: string;
    heroSubtitle: string;
    heroPrimaryLabel: string;
    heroSecondaryLabel: string;
    eventsTitle: string;
    eventsIntro: string;
    exploreEyebrow: string;
    exploreTitle: string;
    exploreIntro: string;
  };
  /**
   * Optional homepage hero background image.
   */
  heroImage?: (number | null) | Media;
  heroPrimaryHref: string;
  heroSecondaryHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  /**
   * Drag items to change their order in the website header.
   */
  items: {
    /**
     * Use a site path such as /about or /#events, or a full external URL.
     */
    href: string;
    en: string;
    lv: string;
    newTab?: boolean | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  en: {
    tagline: string;
    address: string;
    rights: string;
  };
  lv: {
    tagline: string;
    address: string;
    rights: string;
  };
  /**
   * Drag items to change their order in the website footer.
   */
  items: {
    /**
     * Use a path such as /privacy, /terms, or a full external URL.
     */
    href: string;
    en: string;
    lv: string;
    newTab?: boolean | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  en?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroSubtitle?: T;
        heroPrimaryLabel?: T;
        heroSecondaryLabel?: T;
        eventsTitle?: T;
        eventsIntro?: T;
        exploreEyebrow?: T;
        exploreTitle?: T;
        exploreIntro?: T;
      };
  lv?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroSubtitle?: T;
        heroPrimaryLabel?: T;
        heroSecondaryLabel?: T;
        eventsTitle?: T;
        eventsIntro?: T;
        exploreEyebrow?: T;
        exploreTitle?: T;
        exploreIntro?: T;
      };
  heroImage?: T;
  heroPrimaryHref?: T;
  heroSecondaryHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        href?: T;
        en?: T;
        lv?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  en?:
    | T
    | {
        tagline?: T;
        address?: T;
        rights?: T;
      };
  lv?:
    | T
    | {
        tagline?: T;
        address?: T;
        rights?: T;
      };
  items?:
    | T
    | {
        href?: T;
        en?: T;
        lv?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}